### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by ansonla3** [fremantle-capital/tai#15]
I got the following error when executing the run command :  **elixir --sname tai -S mix run --no-halt**
OS: Mac
Elixir version: Elixir 1.7.3 (compiled with Erlang/OTP 21)

```
** (Mix) Could not start application echo_boy: EchoBoy.start(:normal, []) returned an error: shutdown: failed to start child: {:ranch_listener_sup, EchoBoy.Router.HTTP}
    ** (EXIT) shutdown: failed to start child: :ranch_acceptors_sup
        ** (EXIT) :badarg
{"log":"Application echo_boy exited: EchoBoy.start(:normal, []) returned an error: shutdown: failed to start child: {:ranch_listener_sup, EchoBoy.Router.HTTP}\n    ** (EXIT) shutdown: failed to start child: :ranch_acceptors_sup\n        ** (EXIT) :badarg","logging.googleapis.com/sourceLocation":{"file":"application_controller.erl","line":1935,"function":"application_controller.info_exited/3"},"severity":"INFO","time":"2018-12-13T18:49:50.723Z"}
```

**Comment by rupurt** [comment]
Hi @ansonla3,

Can you post the contents of `config/dev.exs`?

**Comment by rupurt** [comment]
@ansonla3 you'll need to add the adapter & advisor configuration you want. There is an [example](https://github.com/fremantle-capital/tai/blob/master/config/dev.exs.example) configuration file you can reference.

https://github.com/fremantle-capital/tai#configuration

Lmk if you have any other issues getting up and running.

**Comment by ansonla3** [comment]
I got 
```
Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Compiling 4 files (.ex)
Generated tai app
** (Mix) Could not start application echo_boy: EchoBoy.start(:normal, []) returned an error: shutdown: failed to start child: {:ranch_listener_sup, EchoBoy.Router.HTTP}
    ** (EXIT) shutdown: failed to start child: :ranch_acceptors_sup
        ** (EXIT) {:listen_error, EchoBoy.Router.HTTP, :eaddrinuse}
```

the command I used :  ``` BINANCE_API_KEY=xxxxxxx BINANCE_API_SECRET=xxxxxxxx  POLONIEX_API_KEY=xxxxxxxx POLONIEX_API_SECRET=xxxxxxxxxx EXAMPLES=true iex -S mix```

dev.exs


```
use Mix.Config

config :tai, send_orders: false

config :tai,
  advisor_groups: %{
    log_spread: [
      advisor: Examples.Advisors.LogSpread.Advisor,
      factory: Tai.Advisors.Factories.OnePerVenueAndProduct,
      products: "binance.btc_usdt poloniex.btc_usdt"
    ],
    fill_or_kill_orders: [
      advisor: Examples.Advisors.FillOrKillOrders.Advisor,
      factory: Tai.Advisors.Factories.OnePerVenueAndProduct,
      products: "binance.btc_usdt"
    ]
  }

config :tai,
  venues: %{
    binance: [
      adapter: Tai.VenueAdapters.Binance,
      products: "btc_usdt ltc_usdt eth_usdt",
      accounts: %{main: %{}}
    ],
    poloniex: [
      adapter: Tai.VenueAdapters.Poloniex,
      products: "btc_usdt ltc_usdt eth_usdt",
      accounts: %{main: %{}}
    ]
  }

config :tai,
  exchanges: %{
    binance: [
      supervisor: Tai.ExchangeAdapters.Binance.Supervisor,
      accounts: %{main: %{}}
    ],
    poloniex: [
      supervisor: Tai.ExchangeAdapters.Poloniex.Supervisor,
      accounts: %{main: %{}}
    ]
  }

config :echo_boy, port: 4200

config :logger, backends: [{LoggerFileBackend, :file_log}]

config :ex_poloniex,
  api_key:  System.get_env("POLONIEX_API_KEY"),
  api_secret:  System.get_env("POLONIEX_API_SECRET")

config :binance,
  api_key: System.get_env("BINANCE_API_KEY"),
  secret_key: System.get_env("BINANCE_API_SECRET")
```

**Comment by ansonla3** [comment]
O I found out the problem was the port num in use

**Comment by rupurt** [comment]
Can you tail the log while you start with that command and post the output? It should be in `log/dev.log` if you're using the file logger backend.

**Comment by ansonla3** [comment]
```
  (poison) lib/poison/encoder.ex:227: anonymous fn/4 in Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:227: anonymous fn/4 in Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map."-encode/3-lists^foldl/2-0-"/3
    (poison) lib/poison/encoder.ex:228: Poison.Encoder.Map.encode/3
    (poison) lib/poison/encoder.ex:227: anonymous fn/4 in Poison.Encoder.Map.encode/3
Last message: {Tai.Event, %Tai.Events.OrderBookSnapshot{snapshot: %Tai.Markets.OrderBook{asks: %{3487.06670618 => {0.00593546, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 49331.0 => {0.00134373, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 9324.0001008 => {0.01, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3431.60424487 => {0.05828178, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 17971.0 => {0.6, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 4.99e4 => {0.70301548, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 8590.00000051 => {0.01698837, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 13850.76456774 => {0.02126341, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 2.75e4 => {0.001, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 4.95e4 => {0.08582167, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 8500.4532 => {0.001228, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 15376.15847961 => {4.1042e-4, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 7122.05856617 => {0.005, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 12230.05150027 => {0.00514586, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 1.55e4 => {0.20964779, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 16922.43302876 => {0.0037851, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 11550.73104418 => {9.975e-5, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 10400.32864531 => {0.00189053, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3753.66217495 => {0.01423798, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 6669.0 => {0.00149947, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 2.01e4 => {0.10080565, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 19000.00000005 => {0.01216367, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 9.3e3 => {0.04237556, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 40007.0 => {0.00926739, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 5829.88690861 => {0.0012, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 8832.64448189 => {0.3, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3.7e3 => {2.2193978, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 4480.0 => {0.11128031, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 13419.0 => {0.002, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 4319.51980895 => {0.1, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 17214.47902 => {0.5, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 8860.0 => {8.4788e-4, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 13520.0 => {0.03682009, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 4345.75196385 => {6.5997e-4, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 9950.13913026 => {5.025e-4, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 16405.0000003 => {0.001996, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 14107.0 => {0.002, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 9204.0223995 => {0.01219898, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 18305.21728582 => {0.00169043, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 13300.001 => {0.02, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 17989.0 => {0.00229719, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 15592.99999997 => {0.03476696, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 9633.89 => {0.00364527, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 15770.00000001 => {0.00572883, #DateTime<2018-12-14 13:52:51.086146Z>, ...}, 10010.73104418 => {1.0077e-4, ...}, 6470.13647096 => {...}, ...}, bids: %{226.25 => {10.0, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 1.67442345 => {1.0, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3228.86143115 => {0.06518868, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3077.0757792 => {0.02033962, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 0.9248539 => {0.9248539, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 0.01524 => {70397.60034383, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3010.16732343 => {0.16610372, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3275.0 => {1.15164258, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 2919.79101479 => {0.00856225, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3107.18898926 => {9.655e-4, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 105.00000005 => {0.23809523, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 2950.51223991 => {0.06778484, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 1510.99999992 => {2.6738e-4, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3100.00000002 => {0.05, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3097.61754336 => {0.01966107, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 2.222e-5 => {58612.93249325, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 2685.88929 => {0.96130815, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 103.33523017 => {0.01107564, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3065.0804 => {0.0201, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 2059.38856006 => {0.09, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 0.00114 => {9876.0, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3169.0 => {0.2, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3.72628721 => {0.00232096, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 2257.0 => {0.34, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 2213.0 => {0.00451875, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 6.04550295 => {1.0, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3166.0 => {0.0078964, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 2524.74903618 => {17.81462466, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 0.02 => {1.0e3, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 1630.0 => {0.15, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 2860.0 => {1.70629528, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3093.57487035 => {3.2648e-4, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3272.84861489 => {0.051, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 9.66 => {0.9, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 1786.51248221 => {5.6534e-4, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 212.0 => {5.0, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 1.0e-7 => {1.0e4, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3103.0 => {0.005, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 2653.1348786 => {0.07538253, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 2901.0 => {0.00172354, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 1.6e3 => {0.03125, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3219.0 => {0.02233222, #DateTime<2018-12-14 13:52:51.086146Z>, nil}, 3035.0 => {1.91103789, #DateTime<2018-12-14 13:52:51.086146Z>, ...}, 3000.04185 => {0.0024571, ...}, 3051.0 => {...}, ...}}, symbol: :btc_usdt, venue_id: :poloniex}}
State: :ok
21:52:51.126 [info] Application tai exited: shutdown
```

**Comment by rupurt** [comment]
@ansonla3 there was a json serialization bug. I've just pushed a fix to [master](https://github.com/fremantle-capital/tai/commit/8d91774887ad165f44ba8130c97e0b6d0e7fb8fc) that should fix the issue.

**Comment by ansonla3** [comment]
@rupurt great! it works. thanks

**Comment by rupurt** [comment]
@ansonla3 sweet. Thanks for brining it to my attention 😄
