### ISSUE TITLE
iex -S mix hangs on 'generate tai app'

### ISSUE THREAD

**Issue by AwaitFuture** [fremantle-capital/tai#153]
hi,
It seems that the quickstart you have in your readme doesnt work as intended; it seems like the app hangs indefinitely, I never get the interactive shell back.

```
awaitfuture@DESKTOP-ICGEU3C:~/elixir_projects/tai$ iex -S mix
Erlang/OTP 22 [erts-10.6.4] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1]

==> tai
Compiling 287 files (.ex)
warning: function EchoBoy.Config.port/0 is undefined (module EchoBoy.Config is not available)
  lib/tai/venue_adapters/mock/stream_supervisor.ex:37

Generated tai app
==> tai
Compiling 1 file (.ex)
warning: redefining module Tai (current version loaded from _build/dev/lib/tai/ebin/Elixir.Tai.beam)
  lib/tai.ex:1

Generated tai app
```

```
awaitfuture@DESKTOP-ICGEU3C:~/elixir_projects/tai$ ll
total 17
drwxrwxrwx 1 awaitfuture awaitfuture   512 Aug  2 08:34 ./
drwxrwxrwx 1 awaitfuture awaitfuture   512 Aug  2 08:32 ../
-rw-rw-rw- 1 awaitfuture awaitfuture    97 Aug  2 08:32 .formatter.exs
-rw-rw-rw- 1 awaitfuture awaitfuture   575 Aug  2 08:32 .gitignore
-rw-rw-rw- 1 awaitfuture awaitfuture    77 Aug  2 08:33 .iex.exs
-rw-rw-rw- 1 awaitfuture awaitfuture   477 Aug  2 08:32 README.md
drwxrwxrwx 1 awaitfuture awaitfuture   512 Aug  2 08:34 _build/
drwxrwxrwx 1 awaitfuture awaitfuture   512 Aug  2 08:34 deps/
drwxrwxrwx 1 awaitfuture awaitfuture   512 Aug  2 08:32 lib/
-rw-rw-rw- 1 awaitfuture awaitfuture   584 Aug  2 08:33 mix.exs
-rw-rw-rw- 1 awaitfuture awaitfuture 11779 Aug  2 08:34 mix.lock
drwxrwxrwx 1 awaitfuture awaitfuture   512 Aug  2 08:32 test/
awaitfuture@DESKTOP-ICGEU3C:~/elixir_projects/tai$
```

```
# .iex.exs
Application.put_env(:elixir, :ansi_enabled, true)

import Tai.IEx
```

please let me know if there anything Ive missed or if theres any other information you would like.

**Comment by rupurt** [comment]
Hi @AwaitFuture,

Can you post a copy of your `config.exs` and/or `config/dev.exs`?

**Comment by AwaitFuture** [comment]
I didnt have a config set; I just tried to use one of your example configs, but that didnt seem to get me any closer:
config/config.exs
```
use Mix.Config
# [default: 10_000] [optional] Adapter start timeout in milliseconds
config :tai, adapter_timeout: 60_000

# [default: nil] [optional] Handler to call after all venues & advisors have successfully started on boot
config :tai, after_boot: {Mod, :func_name, []}

# [default: nil] [optional] Handler to call after any venues or advisors have failed to start on boot
config :tai, after_boot_error: {Mod, :func_name, []}

# [default: false] [optional] Flag which enables the forwarding of each order book change set to the system bus
config :tai, broadcast_change_set: true

# [default: false] [optional] Flag which enables the sending of orders to the venue. When this is `false`, it
# acts a safety net by enqueueing and skipping the order transmission to the venue. This is useful in
# development to prevent accidently sending live orders.
config :tai, send_orders: true

# [default: System.schedulers_online] [optional] Number of processes that can forward internal pubsub messages.
# Defaults to the number of CPU's available in the Erlang VM `System.schedulers_online/0`.
config :tai, system_bus_registry_partitions: 2

# [default: %{}] [optional] Map of configured venues. See below for more details.
config :tai, venues: %{}

# [default: %{}] [optional] Map of configured advisor groups. See below for more details.
config :tai, advisor_groups: %{}
```

**Comment by rupurt** [comment]
Take a look at the example configs https://github.com/fremantle-capital/tai/tree/master/config

https://github.com/fremantle-capital/tai/blob/master/config/dev.exs.example is a good starting point. I will make setting up the configuration more clear. Perhaps a generator.

**Comment by AwaitFuture** [comment]
Yep, using appropriate configs fixes hanging indefinitely; thank you.

closing.

**Comment by rupurt** [comment]
Sweet. Glad to hear 🍾 

I've also got another open source project that might be helpful. It's a GUI frontend using tai underneath the hood https://github.com/fremantle-industries/workbench

**Comment by AwaitFuture** [comment]
Hey,
using appropriate configurations did get me beyond generating tai, but Ive run into a new error; I just assumed I needed to clean and recompile the project but I really cant figure out whats going wrong here:

```
** (Mix) Could not start application logger: Logger.App.start(:normal, []) returned an error: shutdown: failed to start child: Logger.BackendSupervisor
    ** (EXIT) an exception was raised:
        ** (RuntimeError) EXIT when installing backend {LoggerFileBackendWithFormatters, :file_log}: an exception was raised:
    ** (UndefinedFunctionError) function LoggerFileBackendWithFormatters.init/1 is undefined (module LoggerFileBackendWithFormatters is not available)
        LoggerFileBackendWithFormatters.init({LoggerFileBackendWithFormatters, :file_log})
        (stdlib) gen_event.erl:473: :gen_event.server_add_handler/4
        (stdlib) gen_event.erl:318: :gen_event.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
            (logger) lib/logger/backend_supervisor.ex:19: anonymous fn/2 in Logger.BackendSupervisor.start_link/1
            (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
            (logger) lib/logger/backend_supervisor.ex:13: Logger.BackendSupervisor.start_link/1
            (stdlib) supervisor.erl:379: :supervisor.do_start_child_i/3
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:349: anonymous fn/3 in :supervisor.start_children/2
            (stdlib) supervisor.erl:1157: :supervisor.children_map/4
            (stdlib) supervisor.erl:315: :supervisor.init_children/2
```
I get this error while running `MIX_ENV=dev iex -S mix` with the configs youve posted. do you have any idea what might be happening here?

**Comment by rupurt** [comment]
Looks like you don't have the file logger dependency installed. You'll need to add it to `mix.exs` https://github.com/fremantle-capital/tai/blob/master/docs/CONFIGURATION.md#logging

**Comment by rupurt** [comment]
Closing issue due to inactivity. Lmk if you still have trouble getting up and running after https://github.com/fremantle-capital/tai/issues/153#issuecomment-667801383
